[template]
description = "Starter template for an scx-based eBPF program with a userspace helper."
ignore = [
  "target/",
  ".cache/",
  ".clangd",
  "compile_commands.json"
]

[hooks]
post = ["./.cargo/hooks/post_gen.sh"]
